remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme


title: [6.S062/ MAS.S10 Generative Artificial Intelligence in K12 Education]
description: [Fall 2023 | MIT CSAIL x MIT Media Lab]
